export const INIT_GAME = 'INIT_GAME';
export const LOAD_GAME = 'LOAD_GAME';
export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const UPDATE_ALL_SCORES = 'UPDATE_ALL_SCORES';
export const UPDATE_INDIVIDUAL_SCORE = 'UPDATE_INDIVIDUAL_SCORE';